apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-td-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend-td-app
  template:
    metadata:
      labels:
        app: frontend-td-app
    spec:
      containers:
      - name: frontend-td-app
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: PROFESOR
          valueFrom:
            configMapKeyRef:
              name: app-td-config
              key: PROFESOR
