name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ vars.GKE_ZONE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - uses: "google-github-actions/setup-gcloud@v2"
      with:
        install_components: "gke-gcloud-auth-plugin"

    - name: Deploy YAMLs to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/nginx-pocho.yml
        
        # Esperar a que el pod esté listo
        kubectl rollout status deployment/frontend-td-app
        
        # Obtener el nombre del pod automáticamente
        POD_NAME=$(kubectl get pods -l app=frontend-td-app -o jsonpath='{.items[0].metadata.name}')
        
        # Copiar el index.html al pod
        kubectl cp index.html $POD_NAME:/usr/share/nginx/html/index.html
